# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cs_questions', '0010_auto_20160530_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('codingioquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_questions.CodingIoQuestion')),
                ('index', models.PositiveIntegerField()),
                ('challenge_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cs_challenge_list.ChallengeList')),
            ],
            bases=('cs_questions.codingioquestion', models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='challengequestion',
            unique_together=set([('challenge_list', 'index')]),
        ),
    ]
