# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_challenge_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListRank',
        ),
        migrations.RemoveField(
            model_name='challengequestion',
            name='question',
        ),
        migrations.AddField(
            model_name='challengelist',
            name='challenge_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_challenge_list.ChallengeQuestion'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='example',
            field=models.TextField(blank=True, null=True, verbose_name='sample for the problem'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='challenge name'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='problem',
            field=models.TextField(null=True, verbose_name='problem description'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='problem_input',
            field=models.CharField(max_length=140, null=True, verbose_name='problem input data'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='problem_output',
            field=models.CharField(max_length=140, null=True, verbose_name='problem output data'),
        ),
        migrations.AddField(
            model_name='challengequestion',
            name='time_limit',
            field=models.IntegerField(null=True, verbose_name='time limit compilation'),
        ),
        migrations.AlterField(
            model_name='challengelistrank',
            name='challenge_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_challenge_list.ChallengeList'),
        ),
    ]
