# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_challenge_list', '0003_challengequestion_supported_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengelist',
            name='challenge_question',
        ),
        migrations.AddField(
            model_name='challengelist',
            name='challenge_question',
            field=models.ManyToManyField(to='cs_challenge_list.ChallengeQuestion'),
        ),
    ]
