# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_challenge_list', '0004_auto_20160523_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestion',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='question name'),
        ),
    ]
