# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0001_initial'),
        ('cs_activities', '0006_auto_20160511_1209'),
        ('cs_questions', '0009_auto_20160522_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFreeAnswerQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_questions.Question')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_questions.question',),
        ),
        migrations.CreateModel(
            name='QuizActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Activity')),
                ('grading_method', models.IntegerField(choices=[(0, 'largest grade of all responses'), (1, 'smallest grade of all responses'), (2, 'mean grade')])),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs_core.ProgrammingLanguage')),
            ],
            options={
                'verbose_name_plural': 'quiz activities',
                'verbose_name': 'quiz activity',
            },
            bases=('cs_activities.activity',),
        ),
        migrations.CreateModel(
            name='QuizActivityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_questions.QuizActivity')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('response_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cs_activities.Response')),
            ],
            options={
                'abstract': False,
            },
            bases=('cs_activities.response',),
        ),
        migrations.RenameField(
            model_name='booleanquestion',
            old_name='answer',
            new_name='answer_key',
        ),
        migrations.RenameField(
            model_name='stringmatchquestion',
            old_name='answer',
            new_name='answer_key',
        ),
        migrations.AlterField(
            model_name='freeanswerquestion',
            name='data_type',
            field=models.CharField(choices=[('file', 'Arbitrary file'), ('image', 'Image file'), ('pdf', 'PDF file'), ('richtext', 'Rich text input'), ('richtext', 'Plain text input')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='quizactivityitem',
            unique_together=set([('quiz', 'index')]),
        ),
    ]
