# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cs_core', '0010_responseitem_response_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseitem',
            name='feedback_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseitem',
            name='response_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseitem',
            name='response_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
