# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 19:44
from __future__ import unicode_literals

import annoying.fields
import cs_pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputBlockProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', annoying.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', cs_pages.models.LanguageChooserBlock()), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('interactive_code', wagtail.wagtailcore.blocks.StructBlock((('language', cs_pages.models.LanguageChooserBlock()), ('code', wagtail.wagtailcore.blocks.TextBlock()), ('block_id', wagtail.wagtailcore.blocks.CharBlock(max_length=50))))), ('skulpt_python_code', wagtail.wagtailcore.blocks.StructBlock((('language', cs_pages.models.LanguageChooserBlock()), ('code', wagtail.wagtailcore.blocks.TextBlock()), ('expected_result', wagtail.wagtailcore.blocks.TextBlock())))), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TutorialProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_pages.TutorialPage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inputblockprogress',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_pages.TutorialProgress'),
        ),
    ]
