# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputblockprogress',
            name='ref',
        ),
    ]
